##### 问题:
我们需要执行矩阵和线性代数方面的操作，比如矩阵乘法、求行列式、解线性方程等。

##### 解决方案:
NumPy库中有一个matrix对象可用来处理这种情况。Matrix对象和3.9节中描述的数组对象有些类似，但是在计算时遵循线性代数规则。下面的例子展示了几个重要的特性：

In [9]:
import numpy as np 
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
print(m)

[[ 1 -2  3]
 [ 0  4  5]
 [ 7  8 -9]]


In [10]:
# Return transpose 
print(m.T)

[[ 1  0  7]
 [-2  4  8]
 [ 3  5 -9]]


In [11]:
# Return inverse 
print(m.I)

[[ 0.33043478 -0.02608696  0.09565217]
 [-0.15217391  0.13043478  0.02173913]
 [ 0.12173913  0.09565217 -0.0173913 ]]


In [12]:
# Create a vector and multiply
v = np.matrix([[2],[3],[4]])
print(v)
print()
print(m * v)

[[2]
 [3]
 [4]]

[[ 8]
 [32]
 [ 2]]


更多的操作可在numpy.linalg子模块中找到。例如：

In [13]:
import numpy.linalg
# Determinant 
numpy.linalg.det(m)

-229.99999999999983

In [14]:
# Eigenvalues 
numpy.linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [15]:
# Solve for x in mx = v 
x = numpy.linalg.solve(m, v)
print(x)

[[0.96521739]
 [0.17391304]
 [0.46086957]]


In [16]:
m * x 

matrix([[2.],
        [3.],
        [4.]])

In [17]:
v

matrix([[2],
        [3],
        [4]])

显然，线性代数是个庞大的课题，远超出了本书的范围。但是，如果需要处理矩阵和向量，NumPy是个很好的起点。请访问(http://www.numpy.org)以获得更多详细的信息。
