##### 问题
我们需要对大型的数据集比如数组或网格（grid）进行计算。

##### 解决方案:
对于任何涉及数组的计算密集型任务，请使用NumPy库。NumPy的主要特性是为Python提供了数组对象，比标准Python中的列表有着更好的性能表现，因此更加适合于做数学计算。下面是一个简短的示例，用来说明列表同NumPy数组在行为上的几个重要不同之处：

In [1]:
#Python lists 
x = [1, 2, 3, 4] 
y = [5, 6, 7, 8] 
x * 2 #每个数值由一个变成了两个


[1, 2, 3, 4, 1, 2, 3, 4]

In [2]:
#x+10 #报错

In [3]:
x + y  

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
# Numpy arrays 
import numpy as numpy 
ax = numpy.array([1, 2, 3, 4]) 
ay = numpy.array([5, 6, 7, 8]) 
print(ax * 2 )
print(ax + 10)  
print(ax + ay) 
print(ax * ay)

[2 4 6 8]
[11 12 13 14]
[ 6  8 10 12]
[ 5 12 21 32]


可以看到，有关数组的几个基本数学运算在行为上都有所不同。特别是，NumPy中的数组在进行标量运算（例如  ax  *  2或ax + 10）时是针对逐个元素进行计算的。

此外，当两个操作数都是数组时，NumPy数组在进行数学运算时会针对数组的所有元素进行计算，并产生出一个新的数组作为结果。

由于数学操作会同时施加于所有的元素之上，这一事实使得对整个数组的计算变得非常简单和快速。比方说，如果想计算多项式的值：

In [5]:
def f(x): 
    return 3*x**2 - 2*x + 7 
f(ax) #对数组中所有的值进行函数运算

array([ 8, 15, 28, 47])

NumPy提供了一些“通用函数”的集合，它们也能对数组进行操作。这些通用函数可作为math模块中所对应函数的替代。示例如下：

In [6]:

print(numpy.sqrt(ax))
print(numpy.cos(ax))

[1.         1.41421356 1.73205081 2.        ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


使用NumPy中的通用函数，其效率要比对数组进行迭代然后使用math模块中的函数每次只处理一个元素快上百倍。因此，只要有可能就应该使用这些通用函数。

在底层，NumPy数组的内存分配方式和C或者Fortran一样。即，它们是大块的连续内存，由同一种类型的数据组成。正是因为这样，NumPy才能创建比通常Python中的列表要大得多的数组。例如，如果想创建一个10000×10000的二维浮点数组，这根本不是问题：

In [1]:
grid = numpy.zeros(shape=(10,10), dtype=float) 
print(grid)

NameError: name 'numpy' is not defined

所有的常用操作仍然可以同时施加于所有的元素之上：

In [8]:
grid =grid+10
print(grid)

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


所有的常用操作仍然可以同时施加于所有的元素之上：

In [9]:
import random
grid =grid+random.randint(0,10)
print(grid)

[[16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]
 [16. 16. 16. 16. 16. 16. 16. 16. 16. 16.]]


In [10]:

print(numpy.sqrt(grid))

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]]


关于NumPy，一个特别值得提起的方面就是NumPy扩展了Python列表的索引功能—尤其是针对多维数组时更是如此。为了说明，我们先构造一个简单的二维数组然后做些试验：

In [11]:
a = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [12]:
# Select row 1 
a[1] #数组从0开始计数

array([5, 6, 7, 8])

In [13]:
# Select column 1 
a[:,1] #数组从0开始计数

array([ 2,  6, 10])

In [14]:
# Select a subregion and change it 
print(a[1:3, 1:3])
print('\n')
a[1:3, 1:3] += 10
print(a)

[[ 6  7]
 [10 11]]


[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]


In [15]:
# Broadcast a row vector across an operation on all rows 
print(a + [100, 101, 102, 103] )
print('\n')
print(a)

[[101 103 105 107]
 [105 117 119 111]
 [109 121 123 115]]


[[ 1  2  3  4]
 [ 5 16 17  8]
 [ 9 20 21 12]]


<li>numpy.where()</li>
<div>numpy.where()分两种调用方式：</div>
<div>1、三个参数np.where(cond,x,y)：满足条件（cond）输出x，不满足输出y</div>
<div>2、一个参数np.where(arry)：输出arry中‘真’值的坐标(‘真’也可以理解为非零)</div>

In [16]:
# Conditional assignment on an array
numpy.where(a < 10, a, 10) #如果小于10输出a,大于10输出10

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

Python中大量的科学和工程类函数库都以NumPy作为基础，它也是广泛使用中的最为庞大和复杂的模块之一。尽管如此，对于NumPy我们还是可以从构建简单的例子开始，逐步试验，最后实现一些有用的应用。

提到NumPy的用法，一个相对来说比较常见的导入方式是import numpy as np，正如我们给出的示例中那样，这么做缩短了名称，方便我们每次在程序中输入。(为了记住numpy，本节代码并没有使用import numpy as np,在日常我么可以这样使用以方便输入)